insert into customers ( first_name, last_name, phone, email) values ( 'Faber', 'Bottelstone', '867-350-8346', 'fbottelstone0@ovh.net');
insert into customers ( first_name, last_name, phone, email) values ( 'Jillene', 'Newlove', '841-643-0822', 'jnewlove1@huffingtonpost.com');
insert into customers (first_name, last_name, phone, email) values ( 'Sybila', 'MacAnespie', '828-273-5752', 'smacanespie2@apple.com');
insert into customers ( first_name, last_name, phone, email) values ( 'Koenraad', 'Bakey', '258-224-7875', 'kbakey3@businessinsider.com');
insert into customers ( first_name, last_name, phone, email) values ( 'Jud', 'Gelsthorpe', '346-257-3357', 'jgelsthorpe4@harvard.edu');
insert into customers ( first_name, last_name, phone, email) values ( 'Reuben', 'Adelberg', '793-632-3412', 'radelberg5@wordpress.org');
insert into customers ( first_name, last_name, phone, email) values ( 'Naomi', 'Nudde', '749-192-7631', 'nnudde6@icio.us');
insert into customers ( first_name, last_name, phone, email) values ( 'Jerad', 'Sherwin', '701-147-9172', 'jsherwin7@techcrunch.com');
insert into customers ( first_name, last_name, phone, email) values ('Olwen', 'Bullock', '643-595-6270', 'obullock8@cnet.com');
insert into customers ( first_name, last_name, phone, email) values ('Drucill', 'Juste', '577-888-4398', 'djuste9@biglobe.ne.jp');
insert into customers ( first_name, last_name, phone, email) values ( 'Jerrome', 'Muffen', '194-274-4807', 'jmuffena@cbslocal.com');
insert into customers ( first_name, last_name, phone, email) values ( 'Alanah', 'Carbett', '200-417-2823', 'acarbettb@howstuffworks.com');
insert into customers ( first_name, last_name, phone, email) values ( 'Pier', 'Brooking', '407-773-6664', 'pbrookingc@ebay.co.uk');
insert into customers ( first_name, last_name, phone, email) values ( 'Cirilo', 'Southeran', '857-168-0786', 'csoutherand@instagram.com');
insert into customers ( first_name, last_name, phone, email) values ( 'Minetta', 'Iozefovich', '119-245-0521', 'miozefoviche@ucoz.com');
insert into customers ( first_name, last_name, phone, email) values ( 'Meredithe', 'Mangham', '243-995-8574', 'mmanghamf@walmart.com');
insert into customers ( first_name, last_name, phone, email) values ( 'Nichole', 'Schaben', '187-306-3195', 'nschabeng@loc.gov');
insert into customers ( first_name, last_name, phone, email) values ( 'Anthe', 'Roskruge', '539-498-0236', 'aroskrugeh@hao123.com');
insert into customers ( first_name, last_name, phone, email) values ( 'Freda', 'Haddock', '246-212-0385', 'fhaddocki@cmu.edu');
insert into customers ( first_name, last_name, phone, email) values ( 'Chantalle', 'Scarasbrick', '802-958-1467', 'cscarasbrickj@seattletimes.com');
insert into customers ( first_name, last_name, phone, email) values ( 'Aguste', 'Coaster', '460-269-6920', 'acoasterk@constantcontact.com');
insert into customers ( first_name, last_name, phone, email) values ('Flora', 'Colegate', '554-825-3015', 'fcolegatel@nydailynews.com');
insert into customers ( first_name, last_name, phone, email) values ('Nicolea', 'Wooder', '540-483-0733', 'nwooderm@t.co');
insert into customers ( first_name, last_name, phone, email) values ( 'Barbra', 'Nano', '333-470-7596', 'bnanon@thetimes.co.uk');
insert into customers ( first_name, last_name, phone, email) values ( 'Nedi', 'O''Donovan', '448-492-6505', 'nodonovano@cyberchimps.com');